name: First Interaction

on:
  issues:
    types: [ opened ]
  pull_request_target:
    types: [ opened ]

jobs:
  trigger-workflow:
    uses: sovity/core-edc-github/.github/workflows/first-interaction.yml@0.14.0_2025-08-21_3
    secrets:
      envGH: ${{ secrets.GITHUB_TOKEN }}