name: First Interaction

on:
  issues:
    types: [ opened ]
  pull_request_target:
    types: [ opened ]

jobs:
  trigger-workflow:
    uses: sovity/core-edc-github/.github/workflows/first-interaction.yml@0.11.1_2025-03-10_2
    secrets:
      envGH: ${{ secrets.GITHUB_TOKEN }}