name: Close Inactive Issues

on:
  workflow_dispatch: # allow manual trigger

jobs:
  trigger-workflow:
    uses: eclipse-edc/.github/.github/workflows/stale-bot.yml@main
    secrets:
      envGH: ${{ secrets.GITHUB_TOKEN }}
