name: Release

on:
  workflow_call:
    inputs:
      publish-autodoc:
        type: boolean
        description: whether publish autodoc or not
        default: false

jobs:

  create-tag:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.set-version.outputs.VERSION }}
      TAG: ${{ steps.set-tag.outputs.TAG }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - id: set-version
        run: |
          VERSION=$(echo ${{ github.ref_name }} | cut -d '/' -f 2)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - uses: sovity/core-edc-github/.github/actions/set-project-version@0.11.1_2025-03-10_2
        with:
          version: ${{ steps.set-version.outputs.VERSION }}
      - shell: bash
        id: set-tag
        run: |
          git config user.name "eclipse-edc-bot"
          git config user.email "edc-bot@eclipse.org"
          
          TAG=v${{ steps.set-version.outputs.VERSION }}

          git add .
          git commit -m "Release Version $TAG" 

          git tag $TAG
          git push --atomic origin ${{ github.ref_name }} $TAG
          
          echo "TAG=$TAG" >> $GITHUB_OUTPUT

  create-github-release:
    needs: [ create-tag ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Create GitHub Release
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1.21.0
        with:
          generateReleaseNotes: true
          tag: ${{ needs.Create-Tag.outputs.TAG }}
          token: ${{ secrets.GITHUB_TOKEN }}
          removeArtifacts: true

  publish-autodoc:
    if: inputs.publish-autodoc == true
    needs: [ create-tag ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.ref_name }}
      - uses: sovity/core-edc-github/.github/actions/publish-autodoc@0.11.1_2025-03-10_2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
