name: publish autodoc

on:
  workflow_call:
    inputs:
      version:
        required: false
        description: "version override"
        type: string

jobs:
  generate-and-deploy-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: sovity/core-edc-github/.github/actions/publish-autodoc@0.11.1_2025-03-10_2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
