name: "Publish Snapshot Build"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  Publish-Snapshot:
    name: "Publish artefacts to Snapshots repository"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      # Check out the actions repo so local action references resolve
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: sovity/core-edc-github
          ref: ${{ github.job_workflow_sha }}
          path: .reusable-actions
      - uses: ./.reusable-actions/.github/actions/setup-build
      - uses: ./.reusable-actions/.github/actions/publish-maven-artifacts
        with:
          gpg-private-key: ${{ secrets.ORG_GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.ORG_GPG_PASSPHRASE }}
          username: ${{ secrets.CENTRAL_SONATYPE_TOKEN_USERNAME }}
          password: ${{ secrets.CENTRAL_SONATYPE_TOKEN_PASSWORD }}

