name: publish swagger ui

on:
  workflow_call:

jobs:
  generate-openapi-spec:
    runs-on: ubuntu-latest
    outputs:
      api_groups: ${{ steps.outputStep.outputs.matrix }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: eclipse-edc/.github/.github/actions/setup-build@main
      - name: Generate API Specs
        run: ./gradlew resolve
      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
        with:
          name: openapi-spec
          path: resources/openapi/yaml
      - name: get api groups and create matrix for next job
        id: outputStep
        run: |
          if test -d resources/openapi/yaml; then
            API_GROUPS_ARRAY=$(ls -l resources/openapi/yaml | grep '^d' | awk '{print $9}' | sed ':a; N; $!ba; s/\n/","/g' | sed 's/.*/["&"]/')
            echo "matrix={\"apiGroup\": ${API_GROUPS_ARRAY}}" >> $GITHUB_OUTPUT
          fi

  generate-swagger-ui:
    if: ${{ needs.generate-openapi-spec.outputs.api_groups != '' }}
    needs: generate-openapi-spec
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.generate-openapi-spec.outputs.api_groups) }}
    env:
      rootDir: resources/openapi/yaml/${{ matrix.apiGroup }}
      versionFile: resources/openapi/${{ matrix.apiGroup }}.version
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: eclipse-edc/.github/.github/actions/setup-build@main
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: openapi-spec
          path: resources/openapi/yaml

      - name: Set VERSION environment variable
        run: |
          if [ -f ${{ env.versionFile }} ]; then
            VERSION=$(cat ${{ env.versionFile }} | xargs cat | jq '.[] | select(.maturity=="stable" or .maturity==null) | .version' | cut -d '"' -f 2)
            echo "${{ matrix.apiGroup }} file found. Version: $VERSION"
          else
            VERSION=$(grep version= gradle.properties | cut -c 9-)
            echo "No version.json file found for ${{ matrix.apiGroup }} api context. Project version $VERSION will be used"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Generate API Specs
        run: |
          ./gradlew mergeOpenApiSpec --inputDir=${PWD}/${{ env.rootDir }} --output=${{ matrix.apiGroup }}.yaml --infoTitle="${{ matrix.apiGroup }}" --infoDescription="REST API documentation for the ${{ matrix.apiGroup }}" --infoVersion=${{ env.VERSION }}

      - name: Generate Swagger UI current version
        uses: Legion2/swagger-ui-action@eff65dc3f193f0a749872be82f74baa35be0797d # v1
        with:
          output: swagger-ui/${{ matrix.apiGroup }}/${{ env.VERSION }}
          spec-file: ${{ matrix.apiGroup }}.yaml
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Swagger UI stable version
        uses: Legion2/swagger-ui-action@eff65dc3f193f0a749872be82f74baa35be0797d # v1
        if: ${{ !endsWith( env.VERSION, '-SNAPSHOT') }}
        with:
          output: swagger-ui/${{ matrix.apiGroup }}
          spec-file: ${{ matrix.apiGroup }}.yaml
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
        with:
          name: ${{ matrix.apiGroup }}
          path: swagger-ui

  deploy-swagger-ui:
    needs: generate-swagger-ui
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          path: openapi
          pattern: "*-api"
          merge-multiple: true
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          keep_files: true
