name: publish dependencies

on:
  workflow_call:

jobs:
  publish-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: .github/actions/generate-dependencies-file

      - name: prepare deploy
        run: |
          mkdir public
          mv DEPENDENCIES public/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          keep_files: true

  Post-To-Discord:
    needs: [ publish-dependencies ]
    if: "failure()"
    runs-on: ubuntu-latest
    steps:
      - uses: sarisia/actions-status-discord@eb045afee445dc055c18d3d90bd0f244fd062708 # v1.16.0
        with:
          webhook: ${{ secrets.DISCORD_GITHUB_CI_WEBHOOK }}
          status: ${{ needs.publish-dependencies.result }}
          title: "Generate ${{ github.repository }} dependencies"
          username: GitHub Actions
