name: publish autodoc

on:
  workflow_call:
    inputs:
      version:
        required: false
        description: "version override"
        type: string

jobs:
  generate-and-deploy-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: sovity/core-edc-github/.github/actions/publish-autodoc@0.15.0_2025-12-05_3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
